name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: self-hosted

    steps:
    - uses: actions/checkout@v3
      with:
        submodules: true
    - name: Build
      run: cargo build --verbose --release
    - name: Archive production artifacts
      uses: actions/upload-artifact@v3
      with:
        name: sims-cli-${{env.RUNNER_OS}}-${{env.RUNNER_ARCH}}
        path: |
          target/release/cs4471-sims-cli-client
